
CREATE USER ghost WITH PASSWORD 'rider';
CREATE DATABASE chackra_db;
GRANT ALL PRIVILEGES ON DATABASE chackra_db TO ghost;
\c chackra_db
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ghost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ghost;
